### ISSUE TITLE
not being able to use invsee

### ISSUE THREAD

**Issue by thill19** [DoubleDoorDevelopment/D3Commands#16]
steps to reproduce: use command then take an item out then it breaks (in ssp)

**Comment by thill19** [comment]
[latest.log](https://github.com/DoubleDoorDevelopment/D3Commands/files/2267968/latest.log)

**Comment by Claycorp** [comment]
Partly fixed in dev. There are more issues to deal with as `/invsee` is going to be reworked into a modifiable inventory instead of unmodifiable.
See #17 for other issues for `/invsee` and other 1.12 issues to be fixed.
